@startuml
package entities {
    class CustomerEntity {
        +getId(): String
        +setId(String idToSet)
    }

    class NumberEntity {
        +getId(): String
        +setId(String idToSet)
        +getDdi(): String
        +setDdi(String ddiToSet)
        +getStatus(): NumberStatus
        +setStatus(NumberStatus statusToSet)
        +getCustomer(): CustomerEntity
        +setCustomer(CustomerEntity customerToSet)
    }

    enum NumberStatus {
        DISABLED
        ENABLED
    }

    NumberEntity -left-> "1" NumberStatus
    CustomerEntity "1" *-- "many" NumberEntity
}

package daos {
    interface INumberRepository {
        +findAll(): Flux<NumberEntity>
        +findByCustomerId(Long customerId): Flux<Number>
        +findById(Long Id): Mono<NumberEntity>
    }

   interface ICustomerRepository {
        +findAll(): Flux<CustomerEntity>
        +findById(): Mono<CustomerEntity>
   }

    package impl {
        class KataNumberRepositoryImpl {
            -{static} List<NumberEntity> numberEntitiesDataSource
        }
        class KataCustomerRepositoryImpl {
            -{static} List<CustomerEntity> customerEntitiesDataSource
        }
    }

    KataNumberRepositoryImpl ..|> INumberRepository: implements
    KataCustomerRepositoryImpl ..|> ICustomerRepository: implements
}

package handlers {
    class NumberHandler {
        +listNumbers(ServerRequest request): Mono<ServerResponse>
        +getNumber(ServerRequest request): Mono<ServerResponse>
        +updateNumber(ServerRequest request): Mono<ServerResponse>
    }

    class CustomerHandler {
        +listCustomers(ServerRequest request): Mono<ServerResponse>
        +getCustomer(ServerRequest request): Mono<ServerResponse>
        +getNumbers(ServerRequest request): Mono<ServerResponse>
    }
}

NumberHandler .up.> KataNumberRepositoryImpl: create
CustomerHandler .up.> KataNumberRepositoryImpl: create
CustomerHandler .up.> KataCustomerRepositoryImpl: create

CustomerHandler ..> INumberRepository
CustomerHandler ..> ICustomerRepository
NumberHandler ..> INumberRepository

@enduml
